In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv(r'train.csv')

In [3]:
train

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0             1              8                  c                   3   
1             2              2                  c                   5   
2             3             10                  e                   1   
3             4             26                  b                   2   
4             5             26                  b                   2   
...         ...            ...                ...                 ...   
318433   318434              6                  a                   6   
318434   318435             24                  a                   1   
318435   318436              7                  a                   4   
318436   318437             11                  b                   2   
318437   318438             19                  a                   7   

       Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                         Z                                  3  radiotherapy   
1                         Z                                  2  radiotherapy   
2                         X                                  2    anesthesia   
3                         Y                                  2  radiotherapy   
4                         Y                                  2  radiotherapy   
...                     ...                                ...           ...   
318433                    X                                  3  radiotherapy   
318434                    X                                  2    anesthesia   
318435                    X                                  3    gynecology   
318436                    Y                                  3    anesthesia   
318437                    Y                                  5    gynecology   

       Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0              R                  F        2.0      31397                7.0   
1              S                  F        2.0      31397                7.0   
2              S                  E        2.0      31397                7.0   
3              R                  D        2.0      31397                7.0   
4              S                  D        2.0      31397                7.0   
...          ...                ...        ...        ...                ...   
318433         Q                  F        4.0      86499               23.0   
318434         Q                  E        4.0        325                8.0   
318435         R                  F        4.0     125235               10.0   
318436         Q                  D        3.0      91081                8.0   
318437         Q                  C        2.0      21641                8.0   

       Type of Admission Severity of Illness  Visitors with Patient    Age  \
0              Emergency             Extreme                      2  51-60   
1                 Trauma             Extreme                      2  51-60   
2                 Trauma             Extreme                      2  51-60   
3                 Trauma             Extreme                      2  51-60   
4                 Trauma             Extreme                      2  51-60   
...                  ...                 ...                    ...    ...   
318433         Emergency            Moderate                      3  41-50   
318434            Urgent            Moderate                      4  81-90   
318435         Emergency               Minor                      3  71-80   
318436            Trauma               Minor                      5  11-20   
318437         Emergency               Minor                      2  11-20   

        Admission_Deposit   Stay  
0                  4911.0   0-10  
1                  5954.0  41-50  
2                  4745.0  31-40  
3                  7272.0  41-50  
4                  5558.0  41-50  
...                   ...    ...  
318433             4144.0  

In [4]:
test = pd.read_csv(r'test.csv')

In [5]:
test

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0        318439             21                  c                   3   
1        318440             29                  a                   4   
2        318441             26                  b                   2   
3        318442              6                  a                   6   
4        318443             28                  b                  11   
...         ...            ...                ...                 ...   
137052   455491             11                  b                   2   
137053   455492             25                  e                   1   
137054   455493             30                  c                   3   
137055   455494              5                  a                   1   
137056   455495              6                  a                   6   

       Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                         Z                                  3    gynecology   
1                         X                                  2    gynecology   
2                         Y                                  3    gynecology   
3                         X                                  3    gynecology   
4                         X                                  2    gynecology   
...                     ...                                ...           ...   
137052                    Y                                  4    anesthesia   
137053                    X                                  2  radiotherapy   
137054                    Z                                  2    anesthesia   
137055                    X                                  2    anesthesia   
137056                    X                                  3    gynecology   

       Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0              S                  A        2.0      17006                2.0   
1              S                  F        2.0      17006                2.0   
2              Q                  D        4.0      17006                2.0   
3              Q                  F        2.0      17006                2.0   
4              R                  F        2.0      17006                2.0   
...          ...                ...        ...        ...                ...   
137052         Q                  D        3.0      41160                3.0   
137053         R                  E        4.0      30985                7.0   
137054         R                  A        4.0      81811               12.0   
137055         R                  E        4.0      57021               10.0   
137056         Q                  F        4.0     126729                3.0   

       Type of Admission Severity of Illness  Visitors with Patient    Age  \
0              Emergency            Moderate                      2  71-80   
1                 Trauma            Moderate                      4  71-80   
2              Emergency            Moderate                      3  71-80   
3                 Trauma            Moderate                      3  71-80   
4                 Trauma            Moderate                      4  71-80   
...                  ...                 ...                    ...    ...   
137052         Emergency               Minor                      4  41-50   
137053         Emergency            Moderate                      2   0-10   
137054            Urgent               Minor                      2   0-10   
137055            Trauma               Minor                      2  41-50   
137056            Trauma             Extreme                      5  51-60   

        Admission_Deposit  
0                  3095.0  
1                  4018.0  
2                  4492.0  
3                  4173.0  
4                  4161.0  
...                   ...  
137052             6313.0  
137053             3510.0  
137054             7

In [6]:
sample = pd.read_csv(r'sample.csv')

In [7]:
sample

case_id  Stay
0        318439  0-10
1        318440  0-10
2        318441  0-10
3        318442  0-10
4        318443  0-10
...         ...   ...
137052   455491  0-10
137053   455492  0-10
137054   455493  0-10
137055   455494  0-10
137056   455495  0-10

[137057 rows x 2 columns]

In [8]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318438 entries, 0 to 318437
Data columns (total 18 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   case_id                            318438 non-null  int64  
 1   Hospital_code                      318438 non-null  int64  
 2   Hospital_type_code                 318438 non-null  object 
 3   City_Code_Hospital                 318438 non-null  int64  
 4   Hospital_region_code               318438 non-null  object 
 5   Available Extra Rooms in Hospital  318438 non-null  int64  
 6   Department                         318438 non-null  object 
 7   Ward_Type                          318438 non-null  object 
 8   Ward_Facility_Code                 318438 non-null  object 
 9   Bed Grade                          318325 non-null  float64
 10  patientid                          318438 non-null  int64  
 11  City_Code_Patient                  3139

In [9]:
train.isna().sum()

case_id                                 0
Hospital_code                           0
Hospital_type_code                      0
City_Code_Hospital                      0
Hospital_region_code                    0
Available Extra Rooms in Hospital       0
Department                              0
Ward_Type                               0
Ward_Facility_Code                      0
Bed Grade                             113
patientid                               0
City_Code_Patient                    4532
Type of Admission                       0
Severity of Illness                     0
Visitors with Patient                   0
Age                                     0
Admission_Deposit                       0
Stay                                    0
dtype: int64

In [10]:
train.describe()

case_id  Hospital_code  City_Code_Hospital  \
count  318438.000000  318438.000000       318438.000000   
mean   159219.500000      18.318841            4.771717   
std     91925.276847       8.633755            3.102535   
min         1.000000       1.000000            1.000000   
25%     79610.250000      11.000000            2.000000   
50%    159219.500000      19.000000            5.000000   
75%    238828.750000      26.000000            7.000000   
max    318438.000000      32.000000           13.000000   

       Available Extra Rooms in Hospital      Bed Grade      patientid  \
count                      318438.000000  318325.000000  318438.000000   
mean                            3.197627       2.625807   65747.579472   
std                             1.168171       0.873146   37979.936440   
min                             0.000000       1.000000       1.000000   
25%                             2.000000       2.000000   32847.000000   
50%                             3.000000       3.000000   65724.500000   
75%                             4.000000       3.000000   98470.000000   
max                            24.000000       4.000000  131624.000000   

       City_Code_Patient  Visitors with Patient  Admission_Deposit  
count      313906.000000          318438.000000      318438.000000  
mean            7.251859               3.284099        4880.749392  
std             4.745266               1.764061        1086.776254  
min             1.000000               0.000000        1800.000000  
25%             4.000000               2.000000        4186.000000  
50%             8.000000               3.000000        4741.000000  
75%             8.000000               4.000000        5409.000000  
max            38.000000              32.000000       11008.000000

In [11]:
train['source'] = 'train'
test['source'] = 'test'

In [12]:
df = pd.concat([train,test])

In [13]:
df

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0             1              8                  c                   3   
1             2              2                  c                   5   
2             3             10                  e                   1   
3             4             26                  b                   2   
4             5             26                  b                   2   
...         ...            ...                ...                 ...   
137052   455491             11                  b                   2   
137053   455492             25                  e                   1   
137054   455493             30                  c                   3   
137055   455494              5                  a                   1   
137056   455495              6                  a                   6   

       Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                         Z                                  3  radiotherapy   
1                         Z                                  2  radiotherapy   
2                         X                                  2    anesthesia   
3                         Y                                  2  radiotherapy   
4                         Y                                  2  radiotherapy   
...                     ...                                ...           ...   
137052                    Y                                  4    anesthesia   
137053                    X                                  2  radiotherapy   
137054                    Z                                  2    anesthesia   
137055                    X                                  2    anesthesia   
137056                    X                                  3    gynecology   

       Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0              R                  F        2.0      31397                7.0   
1              S                  F        2.0      31397                7.0   
2              S                  E        2.0      31397                7.0   
3              R                  D        2.0      31397                7.0   
4              S                  D        2.0      31397                7.0   
...          ...                ...        ...        ...                ...   
137052         Q                  D        3.0      41160                3.0   
137053         R                  E        4.0      30985                7.0   
137054         R                  A        4.0      81811               12.0   
137055         R                  E        4.0      57021               10.0   
137056         Q                  F        4.0     126729                3.0   

       Type of Admission Severity of Illness  Visitors with Patient    Age  \
0              Emergency             Extreme                      2  51-60   
1                 Trauma             Extreme                      2  51-60   
2                 Trauma             Extreme                      2  51-60   
3                 Trauma             Extreme                      2  51-60   
4                 Trauma             Extreme                      2  51-60   
...                  ...                 ...                    ...    ...   
137052         Emergency               Minor                      4  41-50   
137053         Emergency            Moderate                      2   0-10   
137054            Urgent               Minor                      2   0-10   
137055            Trauma               Minor                      2  41-50   
137056            Trauma             Extreme                      5  51-60   

        Admission_Deposit   Stay source  
0                  4911.0   0-10  train  
1                  5954.0  41-50  train  
2                  4745.0  31-40  train  
3                  7272.0  41-50  train  
4                  5558.0  41-50  train  
...                 

In [14]:
df['Hospital_code'].unique()

array([ 8,  2, 10, 26, 23, 32,  1, 22, 16,  9,  6, 29, 12,  3, 21, 28, 27,
       19,  5, 14, 13, 31, 24, 17, 25, 15, 11, 30, 18,  4,  7, 20],
      dtype=int64)

In [15]:
df['Hospital_code'].value_counts()

26    47523
23    38220
19    30036
6     29221
11    24827
14    24715
28    24572
27    20243
9     16360
12    16170
29    16158
32    15252
25    14046
10    13538
15    13326
21    11784
24    11467
3     10277
17     7844
1      7460
5      7448
13     7432
2      7277
30     7215
22     6006
31     5740
8      5284
16     5244
18     5228
20     1962
7      1871
4      1749
Name: Hospital_code, dtype: int64

In [16]:
df['Hospital_type_code'].unique()

array(['c', 'e', 'b', 'a', 'f', 'd', 'g'], dtype=object)

In [17]:
df['Hospital_type_code'].value_counts()

a    204730
b     98884
c     66147
e     35428
d     29048
f     15252
g      6006
Name: Hospital_type_code, dtype: int64

In [18]:
df.groupby('Hospital_code')['Hospital_type_code'].value_counts()

Hospital_code  Hospital_type_code
1              d                      7460
2              c                      7277
3              c                     10277
4              a                      1749
5              a                      7448
6              a                     29221
7              a                      1871
8              c                      5284
9              d                     16360
10             e                     13538
11             b                     24827
12             a                     16170
13             a                      7432
14             a                     24715
15             c                     13326
16             c                      5244
17             e                      7844
18             d                      5228
19             a                     30036
20             b                      1962
21             c                     11784
22             g                      6006
23             a    

In [19]:
df['City_Code_Hospital'].unique()

array([ 3,  5,  1,  2,  6,  9, 10,  4, 11,  7, 13], dtype=int64)

In [20]:
df.groupby(['Hospital_code','Hospital_type_code']).City_Code_Hospital.value_counts()

Hospital_code  Hospital_type_code  City_Code_Hospital
1              d                   10                     7460
2              c                   5                      7277
3              c                   3                     10277
4              a                   4                      1749
5              a                   1                      7448
6              a                   6                     29221
7              a                   4                      1871
8              c                   3                      5284
9              d                   5                     16360
10             e                   1                     13538
11             b                   2                     24827
12             a                   9                     16170
13             a                   5                      7432
14             a                   1                     24715
15             c                   5                     13326
1

In [21]:
df['Hospital_region_code'].value_counts()

X    190849
Y    174707
Z     89939
Name: Hospital_region_code, dtype: int64

In [22]:
df['Available Extra Rooms in Hospital'].value_counts()

2     140895
4     131191
3     130755
5      27602
6      11003
1       7984
7       4107
8       1468
9        327
10        89
11        24
0         22
12        17
21         4
13         3
20         2
14         1
24         1
Name: Available Extra Rooms in Hospital, dtype: int64

In [23]:
df.groupby('Hospital_region_code')['Available Extra Rooms in Hospital'].value_counts()

Hospital_region_code  Available Extra Rooms in Hospital
X                     2                                    56948
                      4                                    56506
                      3                                    56404
                      5                                    11909
                      6                                     4142
                      1                                     2726
                      7                                     1538
                      8                                      546
                      9                                       99
                      10                                      16
                      0                                        7
                      12                                       5
                      11                                       2
                      13                                       1
Y                     2           

In [24]:
df['Department'].value_counts()

gynecology            356688
anesthesia             42358
radiotherapy           41033
TB & Chest disease     13751
surgery                 1665
Name: Department, dtype: int64

In [25]:
df.groupby('Hospital_region_code')['Department'].value_counts()

Hospital_region_code  Department        
X                     gynecology            145718
                      anesthesia             22660
                      radiotherapy           15776
                      TB & Chest disease      6030
                      surgery                  665
Y                     gynecology            138188
                      radiotherapy           17675
                      anesthesia             12837
                      TB & Chest disease      5226
                      surgery                  781
Z                     gynecology             72782
                      radiotherapy            7582
                      anesthesia              6861
                      TB & Chest disease      2495
                      surgery                  219
Name: Department, dtype: int64

In [26]:
df.groupby('Department')['Ward_Type'].value_counts()

Department          Ward_Type
TB & Chest disease  R              5501
                    Q              4136
                    S              3790
                    P               257
                    T                67
anesthesia          R             18121
                    Q             12842
                    S             10702
                    P               511
                    T               182
gynecology          R            142633
                    Q            121823
                    S             84768
                    P              5771
                    T              1681
                    U                12
radiotherapy        R             16108
                    Q             12702
                    S             11393
                    P               631
                    T               199
surgery             R               576
                    Q               543
                    S               513
          

In [27]:
df['Ward_Facility_Code'].value_counts()

F    161470
E     79058
D     74312
C     50279
B     50116
A     40260
Name: Ward_Facility_Code, dtype: int64

In [28]:
df['Bed Grade'].isna().sum()

148

In [29]:
df['Bed Grade'].unique()

array([ 2.,  3.,  4.,  1., nan])

In [30]:
a = df['Bed Grade'].mode()

In [31]:
a

0    2.0
dtype: float64

In [32]:
df['Bed Grade'].fillna(value = 2, inplace = True)

In [33]:
df['Bed Grade'].unique()

array([2., 3., 4., 1.])

In [34]:
df['City_Code_Patient'].value_counts()

8.0     176825
2.0      55681
1.0      37772
7.0      33958
5.0      28978
4.0      22044
9.0      16692
15.0     12804
10.0     11809
6.0       8723
12.0      8124
3.0       5401
23.0      5320
14.0      4218
16.0      3187
21.0      2298
13.0      2228
18.0      2010
20.0      1936
26.0      1522
19.0      1458
25.0      1171
27.0      1032
11.0       933
28.0       714
22.0       534
24.0       514
30.0       194
29.0       192
33.0       121
34.0        96
32.0        95
37.0        78
31.0        67
35.0        30
36.0        29
38.0        18
Name: City_Code_Patient, dtype: int64

In [35]:
df['City_Code_Patient'].isna().sum()

6689

In [36]:
b = df['City_Code_Patient'].mode()

In [37]:
b

0    8.0
dtype: float64

In [38]:
df['City_Code_Patient'].fillna(value = 8, inplace = True)

In [39]:
df['City_Code_Patient'].isna().sum()

0

In [40]:
df['Type of Admission'].value_counts()

Trauma       217672
Emergency    168363
Urgent        69460
Name: Type of Admission, dtype: int64

In [41]:
df.groupby('City_Code_Patient')['Type of Admission'].value_counts()

City_Code_Patient  Type of Admission
1.0                Trauma               20063
                   Emergency            12067
                   Urgent                5642
2.0                Trauma               31206
                   Emergency            15759
                                        ...  
37.0               Trauma                  27
                   Urgent                  13
38.0               Trauma                   9
                   Emergency                7
                   Urgent                   2
Name: Type of Admission, Length: 111, dtype: int64

In [42]:
df.groupby(['Type of Admission','Severity of Illness','Visitors with Patient','Age']).Admission_Deposit.value_counts()

Type of Admission  Severity of Illness  Visitors with Patient  Age     Admission_Deposit
Emergency          Extreme              1                      0-10    5918.0               1
                                                               11-20   2777.0               1
                                                                       3781.0               1
                                                                       4239.0               1
                                                                       4612.0               1
                                                                                           ..
Urgent             Moderate             16                     61-70   6493.0               1
                                                               71-80   4270.0               1
                                                                       5160.0               1
                                                               91

In [43]:
df.corr()

case_id  Hospital_code  \
case_id                            1.000000      -0.024139   
Hospital_code                     -0.024139       1.000000   
City_Code_Hospital                -0.008247       0.127760   
Available Extra Rooms in Hospital  0.023878      -0.058744   
Bed Grade                          0.011787      -0.014664   
patientid                         -0.000235       0.002912   
City_Code_Patient                  0.038150      -0.015171   
Visitors with Patient              0.000818      -0.028168   
Admission_Deposit                 -0.029820       0.046347   

                                   City_Code_Hospital  \
case_id                                     -0.008247   
Hospital_code                                0.127760   
City_Code_Hospital                           1.000000   
Available Extra Rooms in Hospital           -0.045313   
Bed Grade                                   -0.048507   
patientid                                    0.001617   
City_Code_Patient                           -0.025305   
Visitors with Patient                        0.018377   
Admission_Deposit                           -0.034767   

                                   Available Extra Rooms in Hospital  \
case_id                                                     0.023878   
Hospital_code                                              -0.058744   
City_Code_Hospital                                         -0.045313   
Available Extra Rooms in Hospital                           1.000000   
Bed Grade                                                  -0.115326   
patientid                                                   0.001551   
City_Code_Patient                                          -0.008530   
Visitors with Patient                                       0.095790   
Admission_Deposit                                          -0.143479   

                                   Bed Grade  patientid  City_Code_Patient  \
case_id                             0.011787  -0.000235           0.038150   
Hospital_code                      -0.014664   0.002912          -0.015171   
City_Code_Hospital                 -0.048507   0.001617          -0.025305   
Available Extra Rooms in Hospital  -0.115326   0.001551          -0.008530   
Bed Grade                           1.000000   0.000580          -0.006378   
patientid                           0.000580   1.000000           0.000956   
City_Code_Patient                  -0.006378   0.000956           1.000000   
Visitors with Patient               0.089360   0.002865          -0.012093   
Admission_Deposit                   0.071756   0.000033           0.025314   

                                   Visitors with Patient  Admission_Deposit  
case_id                                         0.000818          -0.029820  
Hospital_code                                  -0.028168           0.046347  
City_Code_Hospital                              0.018377          -0.034767  
Available Extra Rooms in Hospital               0.095790          -0.143479  
Bed Grade                                       0.089360           0.071756  
patientid                                       0.002865           0.000033  
City_Code_Patient                              -0.012093           0.025314  
Visitors with Patient                           1.000000          -0.150008  
Admission_Deposit                              -0.150008           1.000000

In [44]:
df

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0             1              8                  c                   3   
1             2              2                  c                   5   
2             3             10                  e                   1   
3             4             26                  b                   2   
4             5             26                  b                   2   
...         ...            ...                ...                 ...   
137052   455491             11                  b                   2   
137053   455492             25                  e                   1   
137054   455493             30                  c                   3   
137055   455494              5                  a                   1   
137056   455495              6                  a                   6   

       Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                         Z                                  3  radiotherapy   
1                         Z                                  2  radiotherapy   
2                         X                                  2    anesthesia   
3                         Y                                  2  radiotherapy   
4                         Y                                  2  radiotherapy   
...                     ...                                ...           ...   
137052                    Y                                  4    anesthesia   
137053                    X                                  2  radiotherapy   
137054                    Z                                  2    anesthesia   
137055                    X                                  2    anesthesia   
137056                    X                                  3    gynecology   

       Ward_Type Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0              R                  F        2.0      31397                7.0   
1              S                  F        2.0      31397                7.0   
2              S                  E        2.0      31397                7.0   
3              R                  D        2.0      31397                7.0   
4              S                  D        2.0      31397                7.0   
...          ...                ...        ...        ...                ...   
137052         Q                  D        3.0      41160                3.0   
137053         R                  E        4.0      30985                7.0   
137054         R                  A        4.0      81811               12.0   
137055         R                  E        4.0      57021               10.0   
137056         Q                  F        4.0     126729                3.0   

       Type of Admission Severity of Illness  Visitors with Patient    Age  \
0              Emergency             Extreme                      2  51-60   
1                 Trauma             Extreme                      2  51-60   
2                 Trauma             Extreme                      2  51-60   
3                 Trauma             Extreme                      2  51-60   
4                 Trauma             Extreme                      2  51-60   
...                  ...                 ...                    ...    ...   
137052         Emergency               Minor                      4  41-50   
137053         Emergency            Moderate                      2   0-10   
137054            Urgent               Minor                      2   0-10   
137055            Trauma               Minor                      2  41-50   
137056            Trauma             Extreme                      5  51-60   

        Admission_Deposit   Stay source  
0                  4911.0   0-10  train  
1                  5954.0  41-50  train  
2                  4745.0  31-40  train  
3                  7272.0  41-50  train  
4                  5558.0  41-50  train  
...                 

In [45]:
final_df = df.drop(columns = ['Ward_Facility_Code','patientid','Stay'])

In [46]:
final_df

case_id  Hospital_code Hospital_type_code  City_Code_Hospital  \
0             1              8                  c                   3   
1             2              2                  c                   5   
2             3             10                  e                   1   
3             4             26                  b                   2   
4             5             26                  b                   2   
...         ...            ...                ...                 ...   
137052   455491             11                  b                   2   
137053   455492             25                  e                   1   
137054   455493             30                  c                   3   
137055   455494              5                  a                   1   
137056   455495              6                  a                   6   

       Hospital_region_code  Available Extra Rooms in Hospital    Department  \
0                         Z                                  3  radiotherapy   
1                         Z                                  2  radiotherapy   
2                         X                                  2    anesthesia   
3                         Y                                  2  radiotherapy   
4                         Y                                  2  radiotherapy   
...                     ...                                ...           ...   
137052                    Y                                  4    anesthesia   
137053                    X                                  2  radiotherapy   
137054                    Z                                  2    anesthesia   
137055                    X                                  2    anesthesia   
137056                    X                                  3    gynecology   

       Ward_Type  Bed Grade  City_Code_Patient Type of Admission  \
0              R        2.0                7.0         Emergency   
1              S        2.0                7.0            Trauma   
2              S        2.0                7.0            Trauma   
3              R        2.0                7.0            Trauma   
4              S        2.0                7.0            Trauma   
...          ...        ...                ...               ...   
137052         Q        3.0                3.0         Emergency   
137053         R        4.0                7.0         Emergency   
137054         R        4.0               12.0            Urgent   
137055         R        4.0               10.0            Trauma   
137056         Q        4.0                3.0            Trauma   

       Severity of Illness  Visitors with Patient    Age  Admission_Deposit  \
0                  Extreme                      2  51-60             4911.0   
1                  Extreme                      2  51-60             5954.0   
2                  Extreme                      2  51-60             4745.0   
3                  Extreme                      2  51-60             7272.0   
4                  Extreme                      2  51-60             5558.0   
...                    ...                    ...    ...                ...   
137052               Minor                      4  41-50             6313.0   
137053            Moderate                      2   0-10             3510.0   
137054               Minor                      2   0-10             7190.0   
137055               Minor                      2  41-50             5435.0   
137056             Extreme                      5  51-60             4702.0   

       source  
0       train  
1       train  
2       train  
3       train  
4       train  
...       ...  
137052   test  
137053   test  
137054   test  
137055   test  
137056   test  

[455495 rows x 16 columns]

In [47]:
df_number_columns = df.select_dtypes(include=np.number).columns

In [48]:
df_number_columns

Index(['case_id', 'Hospital_code', 'City_Code_Hospital',
       'Available Extra Rooms in Hospital', 'Bed Grade', 'patientid',
       'City_Code_Patient', 'Visitors with Patient', 'Admission_Deposit'],
      dtype='object')

In [49]:
df_category_columns = df.select_dtypes(exclude=np.number).columns

In [50]:
df_category_columns

Index(['Hospital_type_code', 'Hospital_region_code', 'Department', 'Ward_Type',
       'Ward_Facility_Code', 'Type of Admission', 'Severity of Illness', 'Age',
       'Stay', 'source'],
      dtype='object')

In [51]:
data_to_encode = df[df_category_columns].drop(columns = ['source','Stay'])

In [52]:
data_to_encode

Hospital_type_code Hospital_region_code    Department Ward_Type  \
0                       c                    Z  radiotherapy         R   
1                       c                    Z  radiotherapy         S   
2                       e                    X    anesthesia         S   
3                       b                    Y  radiotherapy         R   
4                       b                    Y  radiotherapy         S   
...                   ...                  ...           ...       ...   
137052                  b                    Y    anesthesia         Q   
137053                  e                    X  radiotherapy         R   
137054                  c                    Z    anesthesia         R   
137055                  a                    X    anesthesia         R   
137056                  a                    X    gynecology         Q   

       Ward_Facility_Code Type of Admission Severity of Illness    Age  
0                       F         Emergency             Extreme  51-60  
1                       F            Trauma             Extreme  51-60  
2                       E            Trauma             Extreme  51-60  
3                       D            Trauma             Extreme  51-60  
4                       D            Trauma             Extreme  51-60  
...                   ...               ...                 ...    ...  
137052                  D         Emergency               Minor  41-50  
137053                  E         Emergency            Moderate   0-10  
137054                  A            Urgent               Minor   0-10  
137055                  E            Trauma               Minor  41-50  
137056                  F            Trauma             Extreme  51-60  

[455495 rows x 8 columns]

In [53]:
data_to_encoded = pd.get_dummies(data_to_encode)

In [54]:
data_to_encoded

Hospital_type_code_a  Hospital_type_code_b  Hospital_type_code_c  \
0                          0                     0                     1   
1                          0                     0                     1   
2                          0                     0                     0   
3                          0                     1                     0   
4                          0                     1                     0   
...                      ...                   ...                   ...   
137052                     0                     1                     0   
137053                     0                     0                     0   
137054                     0                     0                     1   
137055                     1                     0                     0   
137056                     1                     0                     0   

        Hospital_type_code_d  Hospital_type_code_e  Hospital_type_code_f  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     1                     0   
3                          0                     0                     0   
4                          0                     0                     0   
...                      ...                   ...                   ...   
137052                     0                     0                     0   
137053                     0                     1                     0   
137054                     0                     0                     0   
137055                     0                     0                     0   
137056                     0                     0                     0   

        Hospital_type_code_g  Hospital_region_code_X  Hospital_region_code_Y  \
0                          0                       0                       0   
1                          0                       0                       0   
2                          0                       1                       0   
3                          0                       0                       1   
4                          0                       0                       1   
...                      ...                     ...                     ...   
137052                     0                       0                       1   
137053                     0                       1                       0   
137054                     0                       0                       0   
137055                     0                       1                       0   
137056                     0                       1                       0   

        Hospital_region_code_Z  ...  Age_0-10  Age_11-20  Age_21-30  \
0                            1  ...         0          0          0   
1                            1  ...         0          0          0   
2                            0  ...         0          0          0   
3                            0  ...         0          0          0   
4                            0  ...         0          0          0   
...                        ...  ...       ...        ...        ...   
137052                       0  ...         0          0          0   
137053                       0  ...         1          0          0   
137054                       1  ...         1          0          0   
137055                       0  ...         0          0          0   
137056                       0  ...         0          0          0   

        Age_31-40  Age_41-50  Age_51-60  Age_61-70  Age_71-80  Age_81-90  \
0               0          0          1          0          0          0   
1               0          0          1          0          0          0   
2               0          0          1          0          0          0   
3               0          0          1          0          0   

In [55]:
df_final = pd.concat([data_to_encoded, df[df_number_columns], 
                      df[['source','Stay']]], axis = 1)

In [56]:
df_final

Hospital_type_code_a  Hospital_type_code_b  Hospital_type_code_c  \
0                          0                     0                     1   
1                          0                     0                     1   
2                          0                     0                     0   
3                          0                     1                     0   
4                          0                     1                     0   
...                      ...                   ...                   ...   
137052                     0                     1                     0   
137053                     0                     0                     0   
137054                     0                     0                     1   
137055                     1                     0                     0   
137056                     1                     0                     0   

        Hospital_type_code_d  Hospital_type_code_e  Hospital_type_code_f  \
0                          0                     0                     0   
1                          0                     0                     0   
2                          0                     1                     0   
3                          0                     0                     0   
4                          0                     0                     0   
...                      ...                   ...                   ...   
137052                     0                     0                     0   
137053                     0                     1                     0   
137054                     0                     0                     0   
137055                     0                     0                     0   
137056                     0                     0                     0   

        Hospital_type_code_g  Hospital_region_code_X  Hospital_region_code_Y  \
0                          0                       0                       0   
1                          0                       0                       0   
2                          0                       1                       0   
3                          0                       0                       1   
4                          0                       0                       1   
...                      ...                     ...                     ...   
137052                     0                       0                       1   
137053                     0                       1                       0   
137054                     0                       0                       0   
137055                     0                       1                       0   
137056                     0                       1                       0   

        Hospital_region_code_Z  ...  Hospital_code  City_Code_Hospital  \
0                            1  ...              8                   3   
1                            1  ...              2                   5   
2                            0  ...             10                   1   
3                            0  ...             26                   2   
4                            0  ...             26                   2   
...                        ...  ...            ...                 ...   
137052                       0  ...             11                   2   
137053                       0  ...             25                   1   
137054                       1  ...             30                   3   
137055                       0  ...              5                   1   
137056                       0  ...              6                   6   

        Available Extra Rooms in Hospital  Bed Grade  patientid  \
0                                       3        2.0      31397   
1                                       2        2.0      31397   
2                                       2        2.0      31397   
3                                       2        2.0      31397 

In [57]:
train_preprocessed = df_final[df_final['source'] == 'train']
test_preprocessed = df_final[df_final['source'] == 'test']

In [58]:
del train_preprocessed['source']
train_preprocessed.head()

Hospital_type_code_a  Hospital_type_code_b  Hospital_type_code_c  \
0                     0                     0                     1   
1                     0                     0                     1   
2                     0                     0                     0   
3                     0                     1                     0   
4                     0                     1                     0   

   Hospital_type_code_d  Hospital_type_code_e  Hospital_type_code_f  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     1                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   Hospital_type_code_g  Hospital_region_code_X  Hospital_region_code_Y  \
0                     0                       0                       0   
1                     0                       0                       0   
2                     0                       1                       0   
3                     0                       0                       1   
4                     0                       0                       1   

   Hospital_region_code_Z  ...  case_id  Hospital_code  City_Code_Hospital  \
0                       1  ...        1              8                   3   
1                       1  ...        2              2                   5   
2                       0  ...        3             10                   1   
3                       0  ...        4             26                   2   
4                       0  ...        5             26                   2   

   Available Extra Rooms in Hospital  Bed Grade  patientid  City_Code_Patient  \
0                                  3        2.0      31397                7.0   
1                                  2        2.0      31397                7.0   
2                                  2        2.0      31397                7.0   
3                                  2        2.0      31397                7.0   
4                                  2        2.0      31397                7.0   

   Visitors with Patient  Admission_Deposit   Stay  
0                      2             4911.0   0-10  
1                      2             5954.0  41-50  
2                      2             4745.0  31-40  
3                      2             7272.0  41-50  
4                      2             5558.0  41-50  

[5 rows x 53 columns]

In [59]:
del test_preprocessed['source']
test_preprocessed.head()

Hospital_type_code_a  Hospital_type_code_b  Hospital_type_code_c  \
0                     0                     0                     1   
1                     1                     0                     0   
2                     0                     1                     0   
3                     1                     0                     0   
4                     0                     1                     0   

   Hospital_type_code_d  Hospital_type_code_e  Hospital_type_code_f  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   Hospital_type_code_g  Hospital_region_code_X  Hospital_region_code_Y  \
0                     0                       0                       0   
1                     0                       1                       0   
2                     0                       0                       1   
3                     0                       1                       0   
4                     0                       1                       0   

   Hospital_region_code_Z  ...  case_id  Hospital_code  City_Code_Hospital  \
0                       1  ...   318439             21                   3   
1                       0  ...   318440             29                   4   
2                       0  ...   318441             26                   2   
3                       0  ...   318442              6                   6   
4                       0  ...   318443             28                  11   

   Available Extra Rooms in Hospital  Bed Grade  patientid  City_Code_Patient  \
0                                  3        2.0      17006                2.0   
1                                  2        2.0      17006                2.0   
2                                  3        4.0      17006                2.0   
3                                  3        2.0      17006                2.0   
4                                  2        2.0      17006                2.0   

   Visitors with Patient  Admission_Deposit  Stay  
0                      2             3095.0   NaN  
1                      4             4018.0   NaN  
2                      3             4492.0   NaN  
3                      3             4173.0   NaN  
4                      4             4161.0   NaN  

[5 rows x 53 columns]

In [60]:
train_X = train_preprocessed.drop(columns='Stay')

In [61]:
test_X = test_preprocessed.drop(columns='Stay')

In [62]:
train_y = train_preprocessed['Stay']

In [63]:
train_y = train_y.replace({"0-10": 1, "11-20": 2, "21-30": 3,"31-40": 4,"41-50" : 5,"51-60" : 6,"61-70" : 7, "71-80" : 8 , "81-90" : 9, "91-100": 10,"More than 100 Days" : 11 })





In [64]:
train_y.value_counts()

3     87491
2     78139
4     55159
6     35018
1     23604
5     11743
8     10254
11     6683
9      4838
10     2765
7      2744
Name: Stay, dtype: int64

In [65]:
from sklearn.preprocessing import StandardScaler

In [66]:
sc = StandardScaler()

sc.fit(train_X)
sc.fit(test_X)

StandardScaler()

In [67]:
X_scaled_train = pd.DataFrame(data = sc.transform(train_X), columns = train_X.columns)

X_scaled_train.head()

Hospital_type_code_a  Hospital_type_code_b  Hospital_type_code_c  \
0             -0.899603             -0.528662              2.403877   
1             -0.899603             -0.528662              2.403877   
2             -0.899603             -0.528662             -0.415995   
3             -0.899603              1.891568             -0.415995   
4             -0.899603              1.891568             -0.415995   

   Hospital_type_code_d  Hospital_type_code_e  Hospital_type_code_f  \
0              -0.25969             -0.290380             -0.185284   
1              -0.25969             -0.290380             -0.185284   
2              -0.25969              3.443769             -0.185284   
3              -0.25969             -0.290380             -0.185284   
4              -0.25969             -0.290380             -0.185284   

   Hospital_type_code_g  Hospital_region_code_X  Hospital_region_code_Y  \
0             -0.113033               -0.850314               -0.785276   
1             -0.113033               -0.850314               -0.785276   
2             -0.113033                1.176036               -0.785276   
3             -0.113033               -0.850314                1.273438   
4             -0.113033               -0.850314                1.273438   

   Hospital_region_code_Z  ...  Age_91-100   case_id  Hospital_code  \
0                2.006701  ...   -0.066587 -9.780526      -1.197933   
1                2.006701  ...   -0.066587 -9.780501      -1.892807   
2               -0.498330  ...   -0.066587 -9.780475      -0.966308   
3               -0.498330  ...   -0.066587 -9.780450       0.886688   
4               -0.498330  ...   -0.066587 -9.780425       0.886688   

   City_Code_Hospital  Available Extra Rooms in Hospital  Bed Grade  \
0           -0.566911                          -0.165503   -0.72975   
1            0.077785                          -1.024428   -0.72975   
2           -1.211608                          -1.024428   -0.72975   
3           -0.889260                          -1.024428   -0.72975   
4           -0.889260                          -1.024428   -0.72975   

   patientid  City_Code_Patient  Visitors with Patient  Admission_Deposit  
0  -0.908759           -0.05383              -0.722758           0.038185  
1  -0.908759           -0.05383              -0.722758           1.003244  
2  -0.908759           -0.05383              -0.722758          -0.115410  
3  -0.908759           -0.05383              -0.722758           2.222753  
4  -0.908759           -0.05383              -0.722758           0.636836  

[5 rows x 52 columns]

In [68]:
X_scaled_test = pd.DataFrame(data = sc.transform(test_X), columns = test_X.columns)

X_scaled_test.head()

Hospital_type_code_a  Hospital_type_code_b  Hospital_type_code_c  \
0             -0.899603             -0.528662              2.403877   
1              1.111601             -0.528662             -0.415995   
2             -0.899603              1.891568             -0.415995   
3              1.111601             -0.528662             -0.415995   
4             -0.899603              1.891568             -0.415995   

   Hospital_type_code_d  Hospital_type_code_e  Hospital_type_code_f  \
0              -0.25969              -0.29038             -0.185284   
1              -0.25969              -0.29038             -0.185284   
2              -0.25969              -0.29038             -0.185284   
3              -0.25969              -0.29038             -0.185284   
4              -0.25969              -0.29038             -0.185284   

   Hospital_type_code_g  Hospital_region_code_X  Hospital_region_code_Y  \
0             -0.113033               -0.850314               -0.785276   
1             -0.113033                1.176036               -0.785276   
2             -0.113033               -0.850314                1.273438   
3             -0.113033                1.176036               -0.785276   
4             -0.113033                1.176036               -0.785276   

   Hospital_region_code_Z  ...  Age_91-100   case_id  Hospital_code  \
0                2.006701  ...   -0.066587 -1.732038       0.307627   
1               -0.498330  ...   -0.066587 -1.732013       1.234125   
2               -0.498330  ...   -0.066587 -1.731988       0.886688   
3               -0.498330  ...   -0.066587 -1.731962      -1.429558   
4               -0.498330  ...   -0.066587 -1.731937       1.118313   

   City_Code_Hospital  Available Extra Rooms in Hospital  Bed Grade  \
0           -0.566911                          -0.165503  -0.729750   
1           -0.244563                          -1.024428  -0.729750   
2           -0.889260                          -0.165503   1.571112   
3            0.400134                          -0.165503  -0.729750   
4            2.011876                          -1.024428  -0.729750   

   patientid  City_Code_Patient  Visitors with Patient  Admission_Deposit  
0   -1.28804          -1.105645              -0.722758          -1.642110  
1   -1.28804          -1.105645               0.402568          -0.788083  
2   -1.28804          -1.105645              -0.160095          -0.349504  
3   -1.28804          -1.105645              -0.160095          -0.644666  
4   -1.28804          -1.105645               0.402568          -0.655769  

[5 rows x 52 columns]

In [69]:
from sklearn.metrics import classification_report,confusion_matrix,plot_roc_curve,accuracy_score
from sklearn.linear_model import LogisticRegression

In [70]:
def metrics(y_true,y_pred):
    print('Confusion Matrix:\n', confusion_matrix(y_true, y_pred))
    print('\n\nAccuracy Score:\n', accuracy_score(y_true, y_pred))
    print('\n\nClassification Report: \n', classification_report(y_true, y_pred))


In [71]:

lg = LogisticRegression(max_iter = 1000)

lg.fit(X_scaled_train, train_y)

LogisticRegression(max_iter=1000)

In [72]:
train_pred = lg.predict(X_scaled_train)

test_pred = lg.predict(X_scaled_test)

In [73]:
print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[ 1144 12120  9690   624     0    26     0     0     0     0     0]
 [  555 35449 35135  4392     0  2605     0     0     0     0     3]
 [  436 24935 57939  2815     0  1296     0     1     0     0    69]
 [  244 10880 22397 11307     0 10192     0     0     3     0   136]
 [  113  2659  7002  1053     0   826     0     0     1     0    89]
 [  100  3156  5270  9382     0 16762     0     0     3     0   345]
 [   14   412  1406   375     0   474     0     0     0     0    63]
 [   34   695  1075  2811     0  5000     0     1     2     0   636]
 [   14   189   257   371     0  3598     0     0     0     0   409]
 [    5   165   279   706     0  1246     0     0     1     0   363]
 [   21   277   410   538     0  3031     0     0     5     0  2401]]


Accuracy Score:
 0.3925505121876158


C:\Users\Jiyaudeen\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))




Classification Report: 
               precision    recall  f1-score   support

           1       0.43      0.05      0.09     23604
           2       0.39      0.45      0.42     78139
           3       0.41      0.66      0.51     87491
           4       0.33      0.20      0.25     55159
           5       0.00      0.00      0.00     11743
           6       0.37      0.48      0.42     35018
           7       0.00      0.00      0.00      2744
           8       0.50      0.00      0.00     10254
           9       0.00      0.00      0.00      4838
          10       0.00      0.00      0.00      2765
          11       0.53      0.36      0.43      6683

    accuracy                           0.39    318438
   macro avg       0.27      0.20      0.19    318438
weighted avg       0.37      0.39      0.35    318438



Naïve Bayes Algorithm

In [74]:
from sklearn.naive_bayes import GaussianNB

In [75]:
nb = GaussianNB()

nb.fit(X_scaled_train, train_y)

train_pred = nb.predict(X_scaled_train)

test_pred = nb.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[  314   519     0     0  9799 10867   553    21   232    97  1202]
 [  633  1933     0     0 31027 37975  1685    53   761   303  3769]
 [  463  1288     0     0 40282 37412  2621   103   987   442  3893]
 [  224   584     0     0 18375 29811  1608   113   928   366  3150]
 [   62   116     0     0  5962  4177   510    27   181    98   610]
 [   75   194     0     0  5830 23198  1051   290  1016   349  3015]
 [    6    15     0     0  1105  1074   203    17    60    23   241]
 [   22    39     0     0  1777  5961   443   126   387   115  1384]
 [    4     5     0     0   372  2670   123   195   353    63  1053]
 [    8     4     0     0   474  1439   127    32   132    45   504]
 [    6    14     0     0   458  2276   231   256   439    76  2927]]


Accuracy Score:
 0.11010306558890584


C:\Users\Jiyaudeen\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))




Classification Report: 
               precision    recall  f1-score   support

           1       0.17      0.01      0.02     23604
           2       0.41      0.02      0.05     78139
           3       0.00      0.00      0.00     87491
           4       0.00      0.00      0.00     55159
           5       0.05      0.51      0.09     11743
           6       0.15      0.66      0.24     35018
           7       0.02      0.07      0.03      2744
           8       0.10      0.01      0.02     10254
           9       0.06      0.07      0.07      4838
          10       0.02      0.02      0.02      2765
          11       0.13      0.44      0.21      6683

    accuracy                           0.11    318438
   macro avg       0.10      0.17      0.07    318438
weighted avg       0.14      0.11      0.05    318438



Decision Tree

In [76]:
from sklearn.tree import DecisionTreeClassifier

In [77]:
dt = DecisionTreeClassifier()

dt.fit(X_scaled_train, train_y)

train_pred = dt.predict(X_scaled_train)

test_pred = dt.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[23604     0     0     0     0     0     0     0     0     0     0]
 [    0 78139     0     0     0     0     0     0     0     0     0]
 [    0     0 87491     0     0     0     0     0     0     0     0]
 [    0     0     0 55159     0     0     0     0     0     0     0]
 [    0     0     0     0 11743     0     0     0     0     0     0]
 [    0     0     0     0     0 35018     0     0     0     0     0]
 [    0     0     0     0     0     0  2744     0     0     0     0]
 [    0     0     0     0     0     0     0 10254     0     0     0]
 [    0     0     0     0     0     0     0     0  4838     0     0]
 [    0     0     0     0     0     0     0     0     0  2765     0]
 [    0     0     0     0     0     0     0     0     0     0  6683]]


Accuracy Score:
 1.0


Classification Report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00     23604
           2       1.00      1.00      1.00     

RandomForest Classifier

In [78]:
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier, BaggingClassifier, VotingClassifier

In [79]:
rf = RandomForestClassifier()

rf.fit(X_scaled_train, train_y)

train_pred = rf.predict(X_scaled_train)

test_pred = rf.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[23604     0     0     0     0     0     0     0     0     0     0]
 [    0 78139     0     0     0     0     0     0     0     0     0]
 [    0     0 87491     0     0     0     0     0     0     0     0]
 [    0     0     0 55159     0     0     0     0     0     0     0]
 [    0     0     0     0 11743     0     0     0     0     0     0]
 [    0     0     0     0     0 35018     0     0     0     0     0]
 [    0     0     0     0     0     0  2744     0     0     0     0]
 [    0     0     0     0     0     0     0 10254     0     0     0]
 [    0     0     0     0     0     0     0     0  4838     0     0]
 [    0     0     0     0     0     0     0     0     0  2765     0]
 [    0     0     0     0     0     0     0     0     0     0  6683]]


Accuracy Score:
 1.0


Classification Report: 
               precision    recall  f1-score   support

           1       1.00      1.00      1.00     23604
           2       1.00      1.00      1.00     

BAGGING Classifier

In [80]:
bc = BaggingClassifier()

bc.fit(X_scaled_train, train_y)

train_pred = bc.predict(X_scaled_train)

test_pred = bc.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[23255   184   152    10     1     1     0     0     0     0     1]
 [  115 77473   405    91     2    52     0     1     0     0     0]
 [   99   900 86409    52     6    20     0     0     1     0     4]
 [   59   461   789 53714     3   113     0    12     3     2     3]
 [   37   120   295    83 11189    16     0     3     0     0     0]
 [   25   135   199   271     7 34348     2     9    13     0     9]
 [    3    20    58    23     5    24  2607     0     2     0     2]
 [    8    38    37   105     3   197     1  9856     1     0     8]
 [    3     9     7    30     0    60     1     5  4713     0    10]
 [    4    13    12    25     0    44     0     5     3  2651     8]
 [    5    10    17    33     1    52     0    17    18     2  6528]]


Accuracy Score:
 0.982115827884863


Classification Report: 
               precision    recall  f1-score   support

           1       0.98      0.99      0.99     23604
           2       0.98      0.99 

ADA Boost

In [81]:
abc = AdaBoostClassifier()

abc.fit(X_scaled_train, train_y)

train_pred = abc.predict(X_scaled_train)

test_pred = abc.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[ 2279 10916  9843   500    14    49     0     0     0     0     3]
 [ 3030 32004 35716  4650     7  2639     0     0    17     1    75]
 [ 2707 23357 55962  4009    12  1217     0     0    16     3   208]
 [ 1200 10901 21332 12434    10  8954     0     0    35     3   290]
 [  498  2687  6485  1132     2   785     0     0    17     0   137]
 [  296  3526  5388 10677     7 14092     0     1    66     1   964]
 [   99   463  1303   332     3   407     0     0     8     0   129]
 [   78   921  1094  3191     1  4166     0     1    32     4   766]
 [   31   209   273   509     0  2986     0     4    38     1   787]
 [   23   209   288   790     2  1034     0     2    12     0   405]
 [   36   323   428   658     1  2713     0     0    37     0  2487]]


Accuracy Score:
 0.3746380771139123


C:\Users\Jiyaudeen\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))




Classification Report: 
               precision    recall  f1-score   support

           1       0.22      0.10      0.13     23604
           2       0.37      0.41      0.39     78139
           3       0.41      0.64      0.50     87491
           4       0.32      0.23      0.26     55159
           5       0.03      0.00      0.00     11743
           6       0.36      0.40      0.38     35018
           7       0.00      0.00      0.00      2744
           8       0.12      0.00      0.00     10254
           9       0.14      0.01      0.01      4838
          10       0.00      0.00      0.00      2765
          11       0.40      0.37      0.38      6683

    accuracy                           0.37    318438
   macro avg       0.22      0.20      0.19    318438
weighted avg       0.33      0.37      0.34    318438



Gradient Boosting

In [82]:
gbc = GradientBoostingClassifier()

gbc.fit(X_scaled_train, train_y)

train_pred = gbc.predict(X_scaled_train)

test_pred = gbc.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[ 2877 11877  8735    61     0    53     0     0     0     0     1]
 [ 1416 39491 31439  2604     0  3169     1     0    13     0     6]
 [ 1146 25553 58216   824     1  1429     1     6   205     2   108]
 [  661 10220 22556  8962     1 12471     1    23    74     2   188]
 [  316  2398  7304   523    30  1023     0     4    43    10    92]
 [  277  2859  5217  5666     1 19538     1    32   933     5   489]
 [   55   382  1452   158     0   508    45     9    52     2    81]
 [   89   683  1123  1533     0  5721     0   109   152     4   840]
 [   43   190   240   256     0  2477     0    14  1145     1   472]
 [   29   154   300   347     0  1477     0    15    24    85   334]
 [   64   280   383   307     1  2168     0    48   576    15  2841]]


Accuracy Score:
 0.4187282924776566


Classification Report: 
               precision    recall  f1-score   support

           1       0.41      0.12      0.19     23604
           2       0.42      0.51

In [83]:
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

XGBClassifier

In [84]:
xgb = XGBClassifier()

xgb.fit(X_scaled_train, train_y)

train_pred = xgb.predict(X_scaled_train)

test_pred = xgb.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

C:\Users\Jiyaudeen\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[09:19:26] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:1095: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\Users\Jiyaudeen\anaconda3\lib\site-packages\xgboost\data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(


Train Metrics
Confusion Matrix:
 [[ 4746 10824  7850   110     9    60     0     1     0     0     4]
 [ 1780 42245 28481  3279     4  2311     1    15    10     0    13]
 [ 1447 22925 60601  1046     8  1266     1    10   112     1    74]
 [  833  9238 22506 14094    12  8212     2    87    59     5   111]
 [  371  2030  7372   704   308   848     0    17    26     5    62]
 [  385  2481  5042  6523     9 19758     0    61   408     8   343]
 [   56   325  1444   211     1   463   160    10    23     1    50]
 [  127   562  1102  1851     2  5022     0   974   121     2   491]
 [   47   162   236   426     1  1709     0    18  1950     1   288]
 [   30   120   274   403     0  1336     1    41    32   326   202]
 [   60   205   337   398     2  1641     0    69   303     8  3660]]


Accuracy Score:
 0.4673500021982301


Classification Report: 
               precision    recall  f1-score   support

           1       0.48      0.20      0.28     23604
           2       0.46      0.54

CatBoostClassifier

In [85]:
cbc = CatBoostClassifier()

cbc.fit(X_scaled_train, train_y)

train_pred = cbc.predict(X_scaled_train)

test_pred = cbc.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Learning rate set to 0.106164
0:	learn: 2.2195307	total: 1.1s	remaining: 18m 22s
1:	learn: 2.1018245	total: 1.92s	remaining: 15m 58s
2:	learn: 2.0152609	total: 2.85s	remaining: 15m 45s
3:	learn: 1.9488221	total: 3.73s	remaining: 15m 28s
4:	learn: 1.8941819	total: 4.53s	remaining: 15m 1s
5:	learn: 1.8493323	total: 5.37s	remaining: 14m 49s
6:	learn: 1.8112522	total: 6.29s	remaining: 14m 51s
7:	learn: 1.7769428	total: 7.13s	remaining: 14m 44s
8:	learn: 1.7502684	total: 7.95s	remaining: 14m 35s
9:	learn: 1.7259093	total: 8.75s	remaining: 14m 26s
10:	learn: 1.7059800	total: 9.57s	remaining: 14m 20s
11:	learn: 1.6896864	total: 10.4s	remaining: 14m 17s
12:	learn: 1.6753993	total: 11.3s	remaining: 14m 21s
13:	learn: 1.6610641	total: 12.1s	remaining: 14m 15s
14:	learn: 1.6502301	total: 12.9s	remaining: 14m 9s
15:	learn: 1.6389516	total: 13.7s	remaining: 14m 4s
16:	learn: 1.6291425	total: 14.6s	remaining: 14m 1s
17:	learn: 1.6213746	total: 15.4s	remaining: 13m 57s
18:	learn: 1.6142923	total: 16.

153:	learn: 1.5017971	total: 2m 4s	remaining: 11m 22s
154:	learn: 1.5015829	total: 2m 4s	remaining: 11m 21s
155:	learn: 1.5013079	total: 2m 5s	remaining: 11m 20s
156:	learn: 1.5010927	total: 2m 6s	remaining: 11m 19s
157:	learn: 1.5008047	total: 2m 7s	remaining: 11m 18s
158:	learn: 1.5005409	total: 2m 8s	remaining: 11m 17s
159:	learn: 1.5003130	total: 2m 8s	remaining: 11m 16s
160:	learn: 1.5000312	total: 2m 9s	remaining: 11m 16s
161:	learn: 1.4998015	total: 2m 10s	remaining: 11m 15s
162:	learn: 1.4995732	total: 2m 11s	remaining: 11m 14s
163:	learn: 1.4993479	total: 2m 12s	remaining: 11m 13s
164:	learn: 1.4991652	total: 2m 12s	remaining: 11m 12s
165:	learn: 1.4989027	total: 2m 13s	remaining: 11m 11s
166:	learn: 1.4986845	total: 2m 14s	remaining: 11m 10s
167:	learn: 1.4985341	total: 2m 15s	remaining: 11m 10s
168:	learn: 1.4983815	total: 2m 16s	remaining: 11m 9s
169:	learn: 1.4981494	total: 2m 16s	remaining: 11m 8s
170:	learn: 1.4977508	total: 2m 17s	remaining: 11m 7s
171:	learn: 1.4974483

305:	learn: 1.4733972	total: 4m 5s	remaining: 9m 16s
306:	learn: 1.4732856	total: 4m 6s	remaining: 9m 16s
307:	learn: 1.4731641	total: 4m 7s	remaining: 9m 15s
308:	learn: 1.4730904	total: 4m 7s	remaining: 9m 14s
309:	learn: 1.4728954	total: 4m 8s	remaining: 9m 13s
310:	learn: 1.4727834	total: 4m 9s	remaining: 9m 12s
311:	learn: 1.4726321	total: 4m 10s	remaining: 9m 12s
312:	learn: 1.4724798	total: 4m 11s	remaining: 9m 11s
313:	learn: 1.4723366	total: 4m 11s	remaining: 9m 10s
314:	learn: 1.4722885	total: 4m 12s	remaining: 9m 9s
315:	learn: 1.4721824	total: 4m 13s	remaining: 9m 8s
316:	learn: 1.4721005	total: 4m 14s	remaining: 9m 7s
317:	learn: 1.4720492	total: 4m 15s	remaining: 9m 7s
318:	learn: 1.4719357	total: 4m 15s	remaining: 9m 6s
319:	learn: 1.4717612	total: 4m 16s	remaining: 9m 5s
320:	learn: 1.4716277	total: 4m 17s	remaining: 9m 4s
321:	learn: 1.4714861	total: 4m 18s	remaining: 9m 3s
322:	learn: 1.4713875	total: 4m 19s	remaining: 9m 2s
323:	learn: 1.4712886	total: 4m 19s	remaini

458:	learn: 1.4551168	total: 6m 7s	remaining: 7m 12s
459:	learn: 1.4550464	total: 6m 7s	remaining: 7m 11s
460:	learn: 1.4549425	total: 6m 8s	remaining: 7m 11s
461:	learn: 1.4548703	total: 6m 9s	remaining: 7m 10s
462:	learn: 1.4547571	total: 6m 10s	remaining: 7m 9s
463:	learn: 1.4546625	total: 6m 11s	remaining: 7m 8s
464:	learn: 1.4545537	total: 6m 11s	remaining: 7m 7s
465:	learn: 1.4543524	total: 6m 12s	remaining: 7m 7s
466:	learn: 1.4542548	total: 6m 13s	remaining: 7m 6s
467:	learn: 1.4540957	total: 6m 14s	remaining: 7m 5s
468:	learn: 1.4539851	total: 6m 15s	remaining: 7m 4s
469:	learn: 1.4538221	total: 6m 15s	remaining: 7m 3s
470:	learn: 1.4537121	total: 6m 16s	remaining: 7m 3s
471:	learn: 1.4535619	total: 6m 17s	remaining: 7m 2s
472:	learn: 1.4534211	total: 6m 18s	remaining: 7m 1s
473:	learn: 1.4532857	total: 6m 19s	remaining: 7m
474:	learn: 1.4531486	total: 6m 19s	remaining: 6m 59s
475:	learn: 1.4530424	total: 6m 20s	remaining: 6m 59s
476:	learn: 1.4530032	total: 6m 21s	remaining: 

611:	learn: 1.4395520	total: 8m 14s	remaining: 5m 13s
612:	learn: 1.4394957	total: 8m 15s	remaining: 5m 12s
613:	learn: 1.4393989	total: 8m 16s	remaining: 5m 11s
614:	learn: 1.4392390	total: 8m 16s	remaining: 5m 11s
615:	learn: 1.4391361	total: 8m 17s	remaining: 5m 10s
616:	learn: 1.4390222	total: 8m 18s	remaining: 5m 9s
617:	learn: 1.4389509	total: 8m 19s	remaining: 5m 8s
618:	learn: 1.4388543	total: 8m 20s	remaining: 5m 7s
619:	learn: 1.4388031	total: 8m 21s	remaining: 5m 7s
620:	learn: 1.4386771	total: 8m 22s	remaining: 5m 6s
621:	learn: 1.4385932	total: 8m 22s	remaining: 5m 5s
622:	learn: 1.4384731	total: 8m 23s	remaining: 5m 4s
623:	learn: 1.4384171	total: 8m 25s	remaining: 5m 4s
624:	learn: 1.4382841	total: 8m 26s	remaining: 5m 3s
625:	learn: 1.4381761	total: 8m 27s	remaining: 5m 3s
626:	learn: 1.4380579	total: 8m 28s	remaining: 5m 2s
627:	learn: 1.4379818	total: 8m 29s	remaining: 5m 1s
628:	learn: 1.4378624	total: 8m 30s	remaining: 5m 1s
629:	learn: 1.4377888	total: 8m 31s	remai

763:	learn: 1.4252169	total: 10m 55s	remaining: 3m 22s
764:	learn: 1.4251561	total: 10m 56s	remaining: 3m 21s
765:	learn: 1.4250514	total: 10m 57s	remaining: 3m 20s
766:	learn: 1.4249655	total: 10m 59s	remaining: 3m 20s
767:	learn: 1.4248818	total: 11m	remaining: 3m 19s
768:	learn: 1.4247762	total: 11m 1s	remaining: 3m 18s
769:	learn: 1.4246638	total: 11m 2s	remaining: 3m 18s
770:	learn: 1.4245665	total: 11m 3s	remaining: 3m 17s
771:	learn: 1.4244771	total: 11m 4s	remaining: 3m 16s
772:	learn: 1.4243787	total: 11m 5s	remaining: 3m 15s
773:	learn: 1.4242938	total: 11m 6s	remaining: 3m 14s
774:	learn: 1.4241964	total: 11m 7s	remaining: 3m 13s
775:	learn: 1.4241186	total: 11m 8s	remaining: 3m 12s
776:	learn: 1.4240431	total: 11m 9s	remaining: 3m 12s
777:	learn: 1.4239888	total: 11m 10s	remaining: 3m 11s
778:	learn: 1.4238965	total: 11m 11s	remaining: 3m 10s
779:	learn: 1.4237690	total: 11m 12s	remaining: 3m 9s
780:	learn: 1.4236630	total: 11m 13s	remaining: 3m 8s
781:	learn: 1.4235864	tot

914:	learn: 1.4118199	total: 13m 9s	remaining: 1m 13s
915:	learn: 1.4117678	total: 13m 10s	remaining: 1m 12s
916:	learn: 1.4116735	total: 13m 11s	remaining: 1m 11s
917:	learn: 1.4116063	total: 13m 12s	remaining: 1m 10s
918:	learn: 1.4115136	total: 13m 12s	remaining: 1m 9s
919:	learn: 1.4114033	total: 13m 13s	remaining: 1m 9s
920:	learn: 1.4113115	total: 13m 14s	remaining: 1m 8s
921:	learn: 1.4112480	total: 13m 15s	remaining: 1m 7s
922:	learn: 1.4111524	total: 13m 16s	remaining: 1m 6s
923:	learn: 1.4110919	total: 13m 16s	remaining: 1m 5s
924:	learn: 1.4110397	total: 13m 17s	remaining: 1m 4s
925:	learn: 1.4109787	total: 13m 18s	remaining: 1m 3s
926:	learn: 1.4109132	total: 13m 19s	remaining: 1m 2s
927:	learn: 1.4108627	total: 13m 20s	remaining: 1m 2s
928:	learn: 1.4107431	total: 13m 21s	remaining: 1m 1s
929:	learn: 1.4106908	total: 13m 21s	remaining: 1m
930:	learn: 1.4105685	total: 13m 22s	remaining: 59.5s
931:	learn: 1.4104929	total: 13m 23s	remaining: 58.6s
932:	learn: 1.4103982	total:

In [88]:
sample['Stay']=test_pred
dict1={'0-10':1,'11-20':2, '21-30':3,
 '31-40':4, '41-50':5, '51-60':6,'61-70':7,'71-80':8,'81-90':9,'91-100':10,'More than 100 Days':11}

In [89]:

sample['Stay']=sample['Stay'].replace(dict1.values(),dict1.keys())
sample.to_csv(r'result.csv',index=False)

LGBMClassifier

In [87]:
lgb = LGBMClassifier()

lgb.fit(X_scaled_train, train_y)

train_pred = lgb.predict(X_scaled_train)

test_pred = lgb.predict(X_scaled_test)

print('Train Metrics')
metrics(train_y, train_pred)

Train Metrics
Confusion Matrix:
 [[ 4112 11232  8093    63     0    61     1     0    14    20     8]
 [ 1828 40770 29661  3250     1  2493     2     5    52    58    19]
 [ 1469 24147 59195  1014     2  1300     5     8   194    70    87]
 [  839  9363 22863 13208     3  8568     7    51    94    33   130]
 [  377  2086  7496   659    90   897     1     6    34    27    70]
 [  365  2560  5132  7383     2 18483     4    39   647    28   375]
 [   60   321  1423   189     0   462   191     6    25     8    59]
 [  126   569  1096  1864     0  5346     2   494   142    27   588]
 [   46   128   192   420     0  2120     2    16  1581     4   329]
 [   24    95   220   384     0  1417     0    27    32   342   224]
 [   62   178   294   365     0  1896     1   105   439    63  3280]]


Accuracy Score:
 0.4451290361074997


Classification Report: 
               precision    recall  f1-score   support

           1       0.44      0.17      0.25     23604
           2       0.45      0.52